[workspace]
members = [
    ".", "compiler",
    "lexer",
    "parser"
]
resolvers = "2"

[package]
name = "sushi"
version = "0.1.0"
edition = "2024"

[dependencies]
lexer = { path = "./lexer" }
parser = { path = "./parser" }
ir = { path = "./ir" }
compiler = { path = "./compiler" }
anyhow = { workspace = true }
argh = "0.1.19"

[workspace.dependencies]
anyhow = "1.0.102"
argh = "0.1.19"
